---
cephadm_rpm_repos:
  - "$basearch"
  - "noarch"
cephadm_ceph_releases:
  - octopus
  - pacific
  - quincy
cephadm_apt_key_url: "https://download.ceph.com/keys/release.asc"
cephadm_apt_key_path: "/usr/local/share/keyrings/ceph.asc"
